name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows the workflow to be manually triggered
  push:
    branches:
      - master  # Replace with 'main' if your default branch is named 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit and Push if Changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dist/snake.svg
          git commit -m "Generated snake animation" || echo "No changes"
          git push